### PR TITLE
chore: update dependencies

### PR DESCRIPTION
**Pull request by benbierens**
18.16 doesn't work reliably in the dist-test cloud environment. It works fine when the docker image is used on my local machine though. Very annoying.

### CODE REVIEW

**Comment by AuHau** [comment]
Have you tried to bump to latest? Would prefer to go forward then backward 😅

**Comment by veaceslavdoina** [comment]
As I remember I also set node to `v18.15.0` in my [PR](56/files#diff-f34da55ca08f1a30591d8b0b3e885bcc678537b2a9a4aadea4f190806b374ddcR2) and it was done because of the known issue - [hardhat compile randomly and quietly stops before compiling contracts #3877](https://github.com/NomicFoundation/hardhat/issues/3877).

Looks like the [issue was fixed in Hardaht v2.16.1](https://github.com/NomicFoundation/hardhat/issues/3877#issuecomment-1610103284).

In our `package.json` we have the following
https://github.com/codex-storage/codex-contracts-eth/blob/b4e4897a37b60d6a9e189b58d4295e9a2d7b6b6a/package.json#L21

**Comment by dryajov** [comment]
> As I remember I also set node to `v18.15.0` in my [PR](56/files#diff-f34da55ca08f1a30591d8b0b3e885bcc678537b2a9a4aadea4f190806b374ddcR2) and it was done because of the known issue - [hardhat compile randomly and quietly stops before compiling contracts #3877](https://github.com/NomicFoundation/hardhat/issues/3877).
> 
> Looks like the [issue was fixed in Hardaht v2.16.1](https://github.com/NomicFoundation/hardhat/issues/3877#issuecomment-1610103284).
> 
> In our `package.json` we have the following
> 
> https://github.com/codex-storage/codex-contracts-eth/blob/b4e4897a37b60d6a9e189b58d4295e9a2d7b6b6a/package.json#L21

Seems quite old, we should definitely bump it. Ot does look like it might be the root cause of the failed builds of the multiarch image?

**Comment by veaceslavdoina** [comment]
> It does look like it might be the root cause of the failed builds of the multiarch image?

Oh. sorry about the issue during the Demo :) I've watched it and added some comments.
It was about `nim-codex:latest` and a temporary tag I've added for Ben to test how can we get the app version :roll_eyes:

**Comment by veaceslavdoina** [comment]
And more notes about upgrading node and modules and results in the branch - [bumb-hardhat-and-hardhat-deploy](https://github.com/codex-storage/codex-contracts-eth/tree/bumb-hardhat-and-hardhat-deploy)
1. I've updated just some modules
   ```
   "hardhat": "^2.17.1",
   "hardhat-deploy": "^0.11.34"
   ```
2. I've updated node to the latest LTS release - Node.js 18.17.0 (Hydrogen/2023-07-18)
    ```shell
    node:18.17.0-alpine3.17
    ```
3. Additional modules update fails and should be investigated
4. Docker Build was tiggerred manually and can be tested
    ```shell
    docker run --rm codexstorage/dist-tests-codex-contracts-eth:sha-d6fbfdc
    ```

**Comment by veaceslavdoina** [comment]
@AuHau added a draft PR and we can consider that only after `hardhat-waffle` package dependencies update - [Ethers v6 support #65](65).

Now, we should probably go wit the [changes proposed above](#issuecomment-1669356357).

**Comment by benbierens** [comment]
`codexstorage/dist-tests-codex-contracts-eth:sha-d6fbfdc`
Passes test on local instance.
Passes test on cloud instance.

**Comment by AuHau** [comment]
> codexstorage/dist-tests-codex-contracts-eth:sha-d6fbfdc
Passes test on local instance.
Passes test on cloud instance.

Is it with the changes from this PR or from [Slava's branch](https://github.com/codex-storage/codex-contracts-eth/tree/bumb-hardhat-and-hardhat-deploy)?

> Now, we should probably go wit the [changes proposed above](https://github.com/codex-storage/codex-contracts-eth/pull/64#issuecomment-1669356357).

Agree, can you create PR and we can close this one in favor of this new PR?

**Comment by veaceslavdoina** [comment]
Probably I will commit my changes in Ben's branch. Or it make sense to create a new PR?

**Comment by AuHau** [comment]
> Probably I will commit my changes in Ben's branch. Or it make sense to create a new PR?

I don't mind either ;-)

**Review by AuHau — APPROVED** [review]

**Pull request merged**
