### PR TITLE
fix(certora): fix failing rule that cancelled requests stay cancelled

### PR DESCRIPTION
**Pull request by 0x-r4bbit**
The prover found a counter example where it starts with a request that has an id `0`, which always results in a `SlotState.New`, resulting in that request becoming `RequestState.Started` while it should be `RequestState.Cancelled`.

We're fixing this by requiring that when the `requestId == 0` then the slot's client has to be `0` address as well.

This will cause a reverting case in the prover, preventing it to find a false positive.

### CODE REVIEW

**Review by AuHau — APPROVED** [review]

**Comment by AuHau** [comment]
Thanks 🙏

**Review by emizzle — COMMENTED** [review]
Could we instead change the require to `requestId != 0 && request.client != 0`?

**Comment by 0x-r4bbit** [comment]
> Could we instead change the require to requestId != 0 && request.client != 0

@emizzle I remember we've considered this in the past. There was a reason why we decided against it, but I can't remember why.. I'll try again and see if it would still do the trick.

**Comment by 0x-r4bbit** [comment]
@emizzle I've updated the PR according to your suggestions and it seems to work fine!

There's three places where we use this rule. Here's individual prover runs for them:

- `allowedRequestStateChanges` - https://prover.certora.com/output/6199/fd25372e06c04fbb8cbf57b0b7b5616d?anonymousKey=f3f799000f1dc0e2d3ca8de71401bd1bd56a0624
- `finishedRequestsStayFinished` - https://prover.certora.com/output/6199/d2a8bca47979470abe79e67a93f17973?anonymousKey=a7cd2976696e930b176ce4e63b4d73121b8eb463
- `cancelledRequestsStayCancelled` - https://prover.certora.com/output/6199/d25a5b14713b445984295a479806a2f0?anonymousKey=ac57b84161fa7c48121a023d85af5e815c0580cd

**Pull request merged**
